language: go
sudo: required
dist: trusty
    # Trusty Tahr seems to be the only way to get
    # a modern version of git on Travis. Once they've
    # upgraded with non-beta, this can be removed along
    # with sudo: required..
os:
    - linux
    - osx
go:
    - 1.5
addons:
    apt:
        packages:
            - git
    

before_install:
    - git config -l
    - git --version
    - hg --version

script:
    - bash test.sh
after_success:
    - bash <(curl -s https://codecov.io/bash)
